stages:
  - build
  - deploy

build:
  stage: build
  script:
    ./mvnw package

artifacts:
  paths:
    - target/Car-Parking-Booking-System-0.0.2-SNAPSHOT.jar

deploy:
  stage: deploy
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku plugins:install java
    - $HEROKU_API_KEY heroku deploy:jar target/Car-Parking-Booking-System-0.0.2-SNAPSHOT.jar -a slot-booking-backend-test

